设计场景:
教案方法内部捕获的checked异常转换成自定义的unchecked异常
直接在方法内部抛出RuntimeException是不明确的

try {
    connection = createConnection(dataSource);
} catch (Exception ex) {
    throw new RuntimeException(ex); // !!
} finally {
    ConnectionHelper.close(connection);
}

public MyConnectionRuntimeException extends RuntimeException {

    public MyConnectionRuntimeException(Exception ex) {
        super(ex);
    }
}

public UnmanagedValueException extends IllegalArgumentException {
    public UnmanagedValueException(String message) {
       super("Unmanaged message:" + message);
    }
}